### PR TITLE
#135 improve java version parsing, add missing dependency

### LINKED ISSUE #131: Reading sheet "xyz" ...Error: NoClassDefFoundError (Java): com/zaxxer/sparsebits/SparseBitSet
When reading in a tab from a particular Excel spreadsheet, I would get the following  error:

	Reading sheet "HISTORICAL BONDS" ...Error: NoClassDefFoundError (Java): com/zaxxer/sparsebits/SparseBitSet

When I downloaded SparseBitSet-1.2.jar and added it to the .../library/XLConnect/java directory, everything worked fine.  Should this jar file be included with the package distribution?  I am running on Windows 10.

### LINKED ISSUE #135: Package not loading after upgrade RStudio to 1.4.1106
Dear colleagues,

After I have been using XLConnect succesfully since I have upgrade RStudio from 1.3 to 1.4.116.

I can install de package.... get this message: 

"package ‘XLConnect’ successfully unpacked and MD5 sums checked
The downloaded binary packages are in
	C:\.....\AppData\Local\Temp\RtmpQHZZwn\downloaded_packages"

But when a try to load it I get the next error:

"Error: package or namespace load failed for ‘XLConnect’:
 .onLoad failed in loadNamespace() for 'XLConnect', details:
  call: if (twoFirst == "1.") {
  error: argumento tiene longitud cero
Además: Warning message:
In system2("java", c("-version"), stdout = TRUE, stderr = TRUE) :
  comando ejecutado '"java" -version' tiene estatus 2"

Any help or suggestions would be appreciate.
Thanks in advance.

### LINKED ISSUE #140: PDF compression in github actions
Despite checking / building the package using `--compact-vignettes=gs+qpdf` in the github actions workflow, the resulting package is larger than expected / possible. Also, the following can be seen during checking on GH actions:
```sh
* checking sizes of PDF files under ‘inst/doc’ ... NOTE
Unable to find GhostScript executable to run checks on size reduction
```
This indicates that at least ghostscript is missing from the environment, possibly qpdf as well.

### PR DESCRIPTION
**Pull request by spoltier**
Closes #135, #125 
Closes #131 
Closes #140 
test xlsx file contributed by @hmamaysky

### CODE REVIEW

**Review by martinstuder — COMMENTED** [review]
I think we'll need to update `java/README` and `inst/COPYRIGHTS` for `SparseBitSet`. Maybe also add a ctb/cph entry to the authors in the DESCRIPTION file?
