### ISSUE TITLE
Errors in running code in vignettes

### ISSUE THREAD

**Issue by thierry-FreeBSD** [miraisolutions/xlconnect#177]
XLConnect is available as a FreeBSD port, and it used to run fine: see https://www.freshports.org/math/R-cran-XLConnect.

But since some days, the tests fail with the hereunder message:

```
* checking running R code from vignettes ... ERROR
Errors in running code in vignettes:
when running code in 'XLConnect.Rnw'
  ...

> if (file.exists("XLConnectExample1.xlsx")) file.remove("XLConnectExample1.xlsx")

> require(XLConnect)

> wb <- loadWorkbook("XLConnectExample1.xlsx", create = TRUE)

  When sourcing 'XLConnect.R':
Error: NoClassDefFoundError (Java): org/apache/poi/openxml4j/exceptions/InvalidFormatException
Execution halted

  'XLConnect.Rnw' using 'UTF-8'... failed
  'XLConnectImpatient.Rnw' using 'latin1'... OK
* checking re-building of vignette outputs ... NOTE
Error(s) in re-building vignettes:
  ...
--- re-building 'XLConnect.Rnw' using Sweave
Loading required package: XLConnect
XLConnect 1.0.5 by Mirai Solutions GmbH [aut],
  Martin Studer [cre],
  The Apache Software Foundation [ctb, cph] (Apache POI),
  Graph Builder [ctb, cph] (Curvesapi Java library),
  Brett Woolridge [ctb, cph] (SparseBitSet Java library)
https://mirai-solutions.ch
https://github.com/miraisolutions/xlconnect

Error: processing vignette 'XLConnect.Rnw' failed with diagnostics:
 chunk 4 (label = simpleEx1) 
Error : NoClassDefFoundError (Java): org/apache/poi/openxml4j/exceptions/InvalidFormatException

--- failed re-building 'XLConnect.Rnw'

--- re-building 'XLConnectImpatient.Rnw' using Sweave
--- finished re-building 'XLConnectImpatient.Rnw'

SUMMARY: processing the following file failed:
  'XLConnect.Rnw'

Error: Vignette re-building failed.
Execution halted

* checking PDF version of manual ... OK
* DONE
Status: 1 ERROR, 2 NOTEs
```
I guess that the problem is caused by the upgrade of some dependency, but I cannot see which one…
Any idea?

**Comment by spoltier** [comment]
Hi @thierry-FreeBSD
I can't see from the page you provided what the previous version was.
XLConnect requires apache POI, we have upgraded to 4.1 since 1.0 in March 2020.
If you're using the version from the master branch, it is now requiring POI 5.2.2, which also upgrades most transitive dependencies. 
The jars are downloaded at load time, there could be an issue with that. 

From the error you provided, the POI dependency is causing the issue.

**Comment by thierry-FreeBSD** [comment]
I'm using POI 4.1.2 with XLConnect 1.0.5, no recent change with them.

**Comment by spoltier** [comment]
Not sure if this will help, but 1.0.6 is now available on CRAN. It uses a newer version of poi.
If the problem persists it must be an issue with downloading the JAR dependencies, which happens the first time the package is loaded.

**Comment by thierry-FreeBSD** [comment]
Thanks for the notification!

I have updated POI to 5.2.3 and XLConnect to 1.0.6 and this is better.

But there remains a problem with vignettes:
`Error: NoClassDefFoundError (Java): org/apache/poi/openxml4j/exceptions/InvalidFormatException`

I shall investigate this problem.

**Comment by martinstuder** [comment]
@thierry-FreeBSD Please let us know if the issue still persists. Also note that XLConnect 1.2.0 is on CRAN now.

**Comment by thierry-FreeBSD** [comment]
[Sorry for the delay]
Yes, after upgrading to 1.2.0, it persists, but with a different message:
```
* checking re-building of vignette outputs ... ERROR
Error(s) in re-building vignettes:
  ...
--- re-building 'XLConnect.Rnw' using Sweave
Loading required package: XLConnect
XLConnect 1.2.0 by Mirai Solutions GmbH [aut],
  Martin Studer [cre],
  The Apache Software Foundation [ctb, cph] (Apache POI),
  Graph Builder [ctb, cph] (Curvesapi Java library),
  Brett Woolridge [ctb, cph] (SparseBitSet Java library)
https://mirai-solutions.ch
https://github.com/miraisolutions/xlconnect

Error: processing vignette 'XLConnect.Rnw' failed with diagnostics:
 chunk 4 (label = simpleEx1) 
Error : NoClassDefFoundError (Java): org/apache/poi/ss/usermodel/Drawing

--- failed re-building 'XLConnect.Rnw'

--- re-building 'XLConnectImpatient.Rnw' using Sweave
--- finished re-building 'XLConnectImpatient.Rnw'

SUMMARY: processing the following file failed:
  'XLConnect.Rnw'

Error: Vignette re-building failed.
Execution halted

```

**Comment by martinstuder** [comment]
Hi @thierry-FreeBSD, it looks like as if a wrong version of POI is in use (just a guess). I'm not familiar with FreeBSD packages, but is it possible that it specifies the wrong runtime dependency version for POI? XLConnect 1.2.0 is based on Apache POI 5.4.0.

```
Runtime dependencies:
R-cran-rJava>0 : [devel/R-cran-rJava](https://www.freshports.org/devel/R-cran-rJava/)
apache-poi>0 : [textproc/apache-poi](https://www.freshports.org/textproc/apache-poi/)
SparseBitSet>0 : [devel/sparsebitset](https://www.freshports.org/devel/sparsebitset/)
apache-xmlbeans>0 : [textproc/apache-xmlbeans](https://www.freshports.org/textproc/apache-xmlbeans/)
apache-commons-io>0 : [devel/apache-commons-io](https://www.freshports.org/devel/apache-commons-io/)
apache-commons-math>0 : [math/apache-commons-math](https://www.freshports.org/math/apache-commons-math/)
apache-commons-codec>0 : [java/apache-commons-codec](https://www.freshports.org/java/apache-commons-codec/)
apache-commons-lang3>0 : [java/apache-commons-lang3](https://www.freshports.org/java/apache-commons-lang3/)
apache-commons-compress>0 : [archivers/apache-commons-compress](https://www.freshports.org/archivers/apache-commons-compress/)
apache-commons-collections4>0 : [java/apache-commons-collections4](https://www.freshports.org/java/apache-commons-collections4/)
R : [math/R](https://www.freshports.org/math/R/)
java : [java/openjdk8](https://www.freshports.org/java/openjdk8/)
```

**Comment by ronaldklop** [comment]
This issue was fixed around Oct, 8th by a change to how the FreeBSD port installs the jar dependencies.
https://cgit.freebsd.org/ports/commit/?id=afd7a4fcb4e32238773ac31b819c22d4f60ba4fc

**Comment by martinstuder** [comment]
Thanks for the info @ronaldklop , much appreciated
